name: Go CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to runner
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

        # Go Build
      - name: Go Build
        working-directory: .
        run: go build -v ./...

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pull-requests: write
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_version: v1.56.2
          fail_on_error: true
          golangci_lint_flags: "--config=.golangci.yml"
          filter_mode: nofilter
          reporter: github-pr-review
          workdir: .

  # go-vulncheck:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #   timeout-minutes: 10
  #   env:
  #     GOWORK: off
  #   steps:
  #     - uses: golang/govulncheck-action@v1
  #       with:
  #         go-version-file: ./backend/go.mod
  #         go-package: ./...
  #         work-dir: ./backend
